### ISSUE TITLE
Troca de nome dos campos nos arquivos de datasets

### ISSUE THREAD

**Issue by vmesel** [RocketChat/hubot-natural#3]
Os datasets em si fazem parte de um classificador só, e como eu já havia comentado com o @diegodorgam os nomes que aparecem nos datasets para frases que dão aquele sentido e suas respostas não estão claros. 

Sugiro a troca dos nomes `classifiers` para `expected_input` e `message` para `possible_answer`

**Comment by diegodorgam** [comment]
nice contribution, after some discussion, we are implementing a new YAML syntax:
`node.name` => `name`
`classifiers` => `expect`
`message` => `answer`

so, a YAML node for the bot corpus would look like this:
```yaml
  - name: rc-cloud
    expect:
      - rocketchat cloud
      - criar meu rocketchat na web
      - deploy rocketchat online
      - rocket chat como serviço
    answer:
      - você pode ter a sua instalação de rocket.chat em segundos na nuvem,
      - visite https://rocket.chat/deploy
      - caso queira saber mais, de uma olhada em rocket.chat/docs/installation/rocket-chat-cloud
    event: respond
    type: block
```
