### ISSUE TITLE
Enable Multi Step Conversations

### ISSUE THREAD

**Issue by clsource** [RocketChat/hubot-natural#5]
Hello, 
The bot works fine, awesome job 👍 
 
but it lacks multi-step conversations.

A sample hubot module for that is

https://github.com/lmarkus/hubot-conversation

With that it could easily be programmed for tasks that require confirmation
or additional parameters.

Thanks for all your efforts 🥇

**Comment by diegodorgam** [comment]
We've just merged a context function implementation that will allow you to this multi-step conversations.

It goes something like this:
```yaml
  - node:
      name: saudacao
    classifiers:
      - ola devi
      - ola pessoal
      - ola
      - como vai voce
      - tudo bom
      - oi como vai
      - tudo bem
    message:
      - olá $user, eu vou bem e você?
      - estou feliz de estar aqui =)
    next:
      interactions:
        - to-mal
        - to-bem
      trust: .8
      # error:
        # - node-name
    event: respond
    type: block

  - node:
      name: almoco
    classifiers:
      - onde tem um restaurante para almoçar
      - tem uma dica de almoço
      - onde encontro um prato feito
      - o almoço ao gratis
    message:
      - Sim, temos almoço nos FoodTrucks
      - e nas redondezas tem um shopping, mas nunca me deixaram ir no shooping
      - acho que as pessoas não estão preparados pra isso...
    event: respond
    type: block

  - node:
      name: programacao-palestra
    classifiers:
      - qual é a programacao de hoje
      - programacao da trilha
      - programacao do evento
    message:
      - A programação do TDC está muito legal!
      - Sei toda ela de cór...
      - quer saber a programação de qual trilha?
    next:
      interactions:
        - quais-trilhas-tem
        - get-programacao
      error:
        - erro-trilha
      trust: .8
    event: respond
    type: block
```
